apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksapp
  namespace: default
spec:
  replicas: #replicaNumber#
  selector:
    matchLabels:
      app: aksapp
  template:
    metadata:
      labels:
        app: aksapp
    spec:
      containers:
      - name: aksapp
        image: digihubcr.azurecr.io/aksapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
